{{- $top := . }}
{{- range $deployment := .Values.deploymentList }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}
  labels:
    app: {{ $deployment.name }}
spec:
  type: {{ $top.Values.service.type }}
  ports:
    - port: {{ $top.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $deployment.name }}
---
{{- end}}