# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

commonConfig:
  environment: dev
  useTimeStampAsLabel: true
  timeStamp: "s1700698160"
  repository: "docker.io"
  resourceKind: "Rollout" # Rollout
  apiVersion: "#argoproj.io/v1alpha1" #argoproj.io/v1alpha1

deploymentList:
  nginx:                     # image name
    name: nginx              # name of service, should be same as image name
    imageTag: latest                  # image tag(required)
    repository: docker.io # image repository(optional, default take value from commonConfig.repository)
    replicas: 2                        # deployment replicas(optional default 1)
 #   cm: test-config                    # configmap(optional)
    extraEnvs:                         # extra environment variables(optional)
      - name: FOO
        value: BAR
    containerPort: 80                  # Container Port(optional, default 8080)
    cpuAllocated: 200m                 # Cpu requests and limits(optional default 1)
    memAllocated: 128Mi                # Memory requests and limits(optional default 1Gi)

strategy:
  Rollout:
    blueGreen:
      activeMetadata:
        labels:
          role: active
      previewMetadata:
        labels:
          role: preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 60

imagePullSecrets: []
imagePullPolicy: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}